---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    vdo.vmware.com/managed-by: vdo
  name: vdo-metrics-reader
rules:
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
